#!/usr/bin/env python3
"""Generate the data tables used by mdparse.

- crates/mdparse/src/entities.rs: HTML5 named character references (source: WHATWG entities.json)
- crates/mdparse/src/unicode.rs: Unicode punctuation/symbol and whitespace ranges (source: Python unicodedata)

Usage: scripts/gen-tables.py [path to entities.json] (downloaded when omitted)
"""

import json
import sys
import unicodedata
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates/mdparse/src"
HEADER = "// Generated by scripts/gen-tables.py. Do not edit by hand.\n\n"


def rust_str(s: str) -> str:
    return '"' + "".join(f"\\u{{{ord(c):x}}}" if not c.isprintable() or c in '"\\' else c for c in s) + '"'


def gen_entities(path: str | None) -> None:
    if path:
        data = json.loads(Path(path).read_text())
    else:
        with urllib.request.urlopen("https://html.spec.whatwg.org/entities.json") as resp:
            data = json.load(resp)
    # CommonMark only accepts names ending with a semicolon
    entries = sorted((name[1:-1], value["characters"]) for name, value in data.items() if name.endswith(";"))
    lines = [f"    ({rust_str(name)}, {rust_str(chars)}),\n" for name, chars in entries]
    (OUT / "entities.rs").write_text(
        HEADER
        + "/// HTML5 named character references (without `&` and `;`), sorted by name.\n"
        + f"pub static ENTITIES: &[(&str, &str); {len(entries)}] = &[\n"
        + "".join(lines)
        + "];\n"
    )
    print(f"entities: {len(entries)}")


def ranges(pred) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in range(0x110000):
        if pred(chr(cp)):
            if out and out[-1][1] == cp - 1:
                out[-1] = (out[-1][0], cp)
            else:
                out.append((cp, cp))
    return out


def rust_ranges(name: str, doc: str, rs: list[tuple[int, int]]) -> str:
    body = "".join(f"    ('\\u{{{a:x}}}', '\\u{{{b:x}}}'),\n" for a, b in rs)
    return f"/// {doc}\npub static {name}: &[(char, char)] = &[\n{body}];\n"


def gen_unicode() -> None:
    punct = ranges(lambda c: unicodedata.category(c)[0] in "PS")
    space = ranges(lambda c: unicodedata.category(c) == "Zs" or c in "\t\n\x0c\r")
    (OUT / "unicode.rs").write_text(
        HEADER
        + f"// Unicode version used for generation: {unicodedata.unidata_version}\n\n"
        + rust_ranges("PUNCTUATION", "Unicode punctuation (P*) and symbol (S*) categories.", punct)
        + "\n"
        + rust_ranges("WHITESPACE", "Unicode whitespace: category Zs plus tab, line feed, form feed and carriage return.", space)
    )
    print(f"punctuation ranges: {len(punct)}, whitespace ranges: {len(space)}")


if __name__ == "__main__":
    gen_entities(sys.argv[1] if len(sys.argv) > 1 else None)
    gen_unicode()
